---
title: "Coding AIPW"
author: "Tim Feeney"
date: '2023-02-20'
output: pdf_document
---

```{r, MESSAGE=FALSE, WARNING=FALSE}
packages<-c("tidyverse")

for (i in packages) {
    library(i,character.only = TRUE)    
}

set.seed(1234)
```

```{r, eval=FALSE, echo=FALSE}
temp<-read.csv("/Users/timf/Desktop/temp.csv")
head(df)
```

### Make simulated data

```{r, eval=FALSE}

n<-695 #same size as dataset we are working with
study_n<-695

#can weight observations or use right seed.

#variables that should have *similar* distributions to the ACTG5202 data
trt<-sample(c("TDF/FTC","ABC/3TC"),size=n,replace = TRUE, prob=c(0.5,0.5))#random treatment assignment in expectation


sex<-rbinom(n,1, prob=0.147)

logrna0<-rnorm(n, 5,0.58)

basecd4<-rnorm(n,186, 165.2)

agegrp<-sample(c(1,2,3), size=n, replace=TRUE, prob = c(0.075, 0.761,0.164))



Y0<-26.14*sex+57.75*logrna0+1.05*basecd4+(-19.72)*agegrp+rnorm(n,0,1)#use the coefficients from the linear regression in the ACTG5202 data

Y1<-Y0+6.7

cd4<-ifelse(trt=="TDF/FTC",Y0, Y1)

df<-data.frame(cd4, trt, sex, logrna0, basecd4, agegrp)
head(df)
#write_csv(df, "sim_data_actg5202_aipw.csv") #output dataset for use by SAS
```


### ITT analysis
```{r}
summary(lm(cd4~trt, data=df))
```
### AIPW
```{r}
aipw_single<-function(data){
    
 pi<-sum(data$trt=="ABC/3TC")/nrow(data)
        ipw<-1/pi
        #model the outcome
        out_model<-lm(cd4~trt+sex+agegrp+basecd4+logrna0, data=data)
        g0<-predict(out_model, newdata=data %>% mutate(trt="TDF/FTC"))
        g1<-predict(out_model, newdata=data %>% mutate(trt="ABC/3TC"))
    
        AIPW0<-(data$cd4*(data$trt=="TDF/FTC")/(1-pi))-(((data$trt=="TDF/FTC")/(1-pi))-1)*g0
        AIPW1<-(data$cd4*(data$trt=="ABC/3TC")/pi)-(((data$trt=="ABC/3TC")/pi)-1)*g1
        
        paste0("AIPW Estimate: ",round(mean(AIPW1)-mean(AIPW0),3)  ) 
}

aipw_single(df)
```



### Bootstrap AIPW Standard Error for CD4 count

```{r}

aipw_sim<-function(data, nsims){
pis<-vector()
mean_diffs<-vector()
    for (i in 1:nsims){
     #random sample from data with size=n, and replacement (ie bootstrap sampling)
        samp<-sample_n(data, size=nrow(data), replace = TRUE) 
        #calculate robability of treatment, ABC/3TC in this sample
        pi<-sum(samp$trt=="ABC/3TC")/nrow(samp)
        ipw<-1/pi
        #model the outcome
        out_model<-lm(cd4~trt+sex+agegrp+basecd4+logrna0, data=samp)
        g0<-predict(out_model, newdata=samp %>% mutate(trt="TDF/FTC"))
        g1<-predict(out_model, newdata=samp %>% mutate(trt="ABC/3TC"))
    
        AIPW0<-(samp$cd4*(samp$trt=="TDF/FTC")/(1-pi))-(((samp$trt=="TDF/FTC")/(1-pi))-1)*g0
        AIPW1<-(samp$cd4*(samp$trt=="ABC/3TC")/pi)-(((samp$trt=="ABC/3TC")/pi)-1)*g1
    
        mean_diffs<-append(mean_diffs, mean(AIPW1)-mean(AIPW0))
     pis<-append(pis, pi)
    }
    data.frame(mean_diffs,pis)
}

aipw_data<-aipw_sim(df_sample, 10000)
head(aipw_data)
mean(aipw_data[,1])

paste0("Bootstrapped SE: ",sd(aipw_data[,1]))

```

### Closed for AIPW Standard Error for CD4 count
```{r, closed form AIPW CI cd4}

#calculate the probabilty of "treatment", pi
        pi<-sum(df$trt=="ABC/3TC")/nrow(df)

#model the outcome
        out_model<-lm(cd4~trt+sex+agegrp+basecd4+logrna0, data=df)
        
#Estimate G-formula for the "untreated" and "treated"
        g0<-predict(out_model, newdata=df %>% mutate(trt="TDF/FTC"))
        g1<-predict(out_model, newdata=df %>% mutate(trt="ABC/3TC"))

#estimate AIPW values for each individual in both 'untreated' and 'treated'
        AIPW0<-(df$cd4*(df$trt=="TDF/FTC")/(1-pi))-(((df$trt=="TDF/FTC")/(1-pi))-1)*g0
        AIPW1<-(df$cd4*(df$trt=="ABC/3TC")/pi)-(((df$trt=="ABC/3TC")/pi)-1)*g1
        
cf_aipw_ate<-mean(AIPW1)-mean(AIPW0)

cf_aipw_diff<-(AIPW1-AIPW0)-cf_aipw_ate
cf_aipw_var<-(1/nrow(df)^2)*sum(cf_aipw_diff^2)
cf_aipw_se<-sqrt(cf_aipw_var)

paste0("Closed-form SE ",cf_aipw_se)
```